# Generated by Django 5.0.6 on 2026-06-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCheckpoint',
            fields=[
                ('source', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'batch_checkpoint',
            },
        ),
        migrations.CreateModel(
            name='BatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(max_length=64)),
                ('rows_exported', models.IntegerField(default=0)),
                ('s3_objects', models.IntegerField(default=0)),
                ('rows_loaded', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=16)),
                ('detail', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'batch_run',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ingested_at', models.DateTimeField(db_index=True)),
                ('customer_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('country', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'src_customers',
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingested_at', models.DateTimeField(db_index=True)),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=8)),
                ('rate_to_usd', models.DecimalField(decimal_places=6, max_digits=14)),
            ],
            options={
                'db_table': 'src_fx_rates',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('ingested_at', models.DateTimeField(db_index=True)),
                ('payment_attempt_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(db_index=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=8)),
                ('status', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'src_payments',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('ingested_at', models.DateTimeField(db_index=True)),
                ('refund_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('payment_id', models.CharField(db_index=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'src_refunds',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('ingested_at', models.DateTimeField(db_index=True)),
                ('subscription_event_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(db_index=True, max_length=64)),
                ('subscription_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(max_length=16)),
                ('plan', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'src_subscription_events',
            },
        ),
        migrations.AddConstraint(
            model_name='fxrate',
            constraint=models.UniqueConstraint(fields=('date', 'currency'), name='uniq_fx_date_currency'),
        ),
    ]
